require_relative "./Fast_Food_Nutrition/version"
require_relative "./Fast_Food_Nutrition/cli"
require_relative "./Fast_Food_Nutrition/scraper"
require_relative "./Fast_Food_Nutrition/restaurant"
require_relative "./Fast_Food_Nutrition/category"
require_relative "./Fast_Food_Nutrition/items"
